[1차 과제 - Step3] 신성준
KUIT-1/atdd-subway pull request #14
Opened 2023-08-20 21:43 UTC by shinsj4653

킹갓 엠페러 마제스티 김정우님의 코드 리뷰 너무 고급져서 눈부시네요..리뷰한 결과를 반영해봤습니다.
# Week1-Step2 Refactoring
## 1. Exception Handling
하나의 exception 폴더를 생성한 후, 커스텀할 수 있는 예외클래스인 SubwayException을 생성하였습니다.
```java
@Getter
public class SubwayException extends RuntimeException{

    private final HttpStatus httpStatus;
    private final String message;
    private final int code;

    public SubwayException(HttpStatus httpStatus, String message, int code) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.code = code;
    }

}
```
이를 기반으로, 여러가지 예외들을 생성하여 활용할 수 있었습니다.  

![image](https://github.com/KUIT-1/atdd-subway/assets/49470452/f6ed3f92-2410-4c83-81f5-3fecf55a4f42)  
ControllerAdvice 에서도 SubwayException이 발견되면 처리되도록 다음과 같이 작성해줬습니다.
```java
@ExceptionHandler(SubwayException.class)
    public ResponseEntity<ErrorResponse> handleSubwayException(SubwayException e) {
        return ResponseEntity.status(e.getHttpStatus()).body(new ErrorResponse(e.getCode(), e.getMessage()));
    }
```
## 2. Station, Line 연관관계 설정
기존에는 Line에 Long 타입으로 downStationId, upStationId을 가지고 있었지만, 1:N 연관관계 매핑을 기반으로 코드를 수정해봤습니다. 
```java
// Line.java
@OneToMany(mappedBy = "line", cascade = CascadeType.ALL)
private List<Station> stations = new ArrayList<>();

// Station.java
@ManyToOne(fetch = LAZY)
@JoinColumn(name = "line_id")
private Line line;
```

## 3. 연관관계 메서드 활용
기존에는 노선 엔티티의 setter 함수를 사용하여 노선 정보를 수정하였습니다.
```java
  // 존재한다면, request 대로 노선 수정
        line.setColor(req.getColor());
        line.setDistance(req.getDistance());
        line.setName(req.getName());
        line.setDownStationId(req.getDownStationId());
        line.setUpStationId(req.getUpStationId());
``` 
객체 지향적으로 코드를 더 개선시키기 위해, 노선 수정용 연관관계 메서드를 생성해줬습니다.
```java
public void updateStations(List<Station> stations) {
        // 현재 노선에 존재하고 있는 역들을 제거
        this.stations.forEach(station -> station.removeLine(this));
        // stations 리스트 clear()
        this.stations.clear();

        this.stations = new ArrayList<>(stations);
        addStations(stations);
    }
```

## 4. DatabaseCleanup 리팩토링
각 엔티티마다 식별자 값이 다를 경우 execute() 함수를 어떤식으로 리팩토링을 해야할지 고민되었습니다. 처음에는 switch case 문을 사용하여 각 테이블에 해당하는 식별자 값을 직접 적용해줬지만, 테이블이 많아질 경우에는 이 방법이 비효율적일 것이라 느껴졌습니다. 리뷰를 받은 결과, `테이블 명` 을 그대로 쿼리문에 적용시키는 방법을 사용하였습니다.
```java
// DatabaseCleanup.java
@Transactional
    public void execute() {
        entityManager.flush();
        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();

        for (String tableName : tableNames) {
                entityManager.createNativeQuery("TRUNCATE TABLE " + tableName).executeUpdate();
                entityManager.createNativeQuery("ALTER TABLE " + tableName + " ALTER COLUMN " + tableName + "_id" + " RESTART WITH 1").executeUpdate();
        }

        entityManager.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
    }
```
# Questions
## 1. 노선 등록시, 상행종점역, 하행종점역 구분방법
```java
@Transactional
    public LineCreateResponse addLine(LineCreateRequest res) {

        Long downStationId = res.getDownStationId();
        Long upStationId = res.getUpStationId();

        // 존재하지 않는 station_id를 추가하려고 하면 예외발생
        Station downStation = validateStationExist(downStationId);
        Station upStation = validateStationExist(upStationId);

        List<Station> stations = new ArrayList<>();
        stations.add(upStation);
        stations.add(downStation);

        // 상행역과 하행역 둘 다 같은 역이면 예외발생
        validateSameStation(downStationId, upStationId);

        // 만약, 둘 다 존재하는 역이라면 노선 생성
        Line line = Line.builder()
                        .color(res.getColor())
                        .distance(res.getDistance())
                        .name(res.getName())
                        .createdDate(LocalDateTime.now())
                        .modifiedDate(LocalDateTime.now()).build();

        line.addStations(stations);
        lineRepository.save(line);

        return new LineCreateResponse("지하철 노선 생성 완료", line.getId());
    }
```
현재 노선 등록시 시, 역들을 상행, 하행 순서로 stations 리스트에 add 한 후, 리스트 자체를 노선에다가 저장해주고 있습니다. 이와 같이 단순히 상행, 하행 순서로 add를 해도 괜찮을지, 아니면 상행 종점인지, 하행 종점인지에 대한 구분이 좀 더 명확히 필요한지 궁금합니다!!

2023-08-21 05:10 UTC, jung-woo-kim requested changes
ㅋㅋㅋㅋ 일취월장한 싱준쓰 코드에 제 눈이 부십니다 🤩
코드 관련 자잘한 리뷰는 일단 남겼습니다.

다만, 로직이 제가 원하는 방향이랑 조금 다르게 가는 것 같아 rc 드려요!
저희 Step3 설명 보면 구간이라는 엔티티가 하나 추가로 필요해요! (line과 station은 일단 다대다 이기 때문에 중간 연결다리가 필요해요)
구간이라는 엔티티에서 상행성 하행선을 갖는 로직입니다.
이렇게 상행역, 하행역을 가지는 구간이라는 엔티티를 만들고, 이것을 line에서 리스트로 가져야 역 순서 개념을 후에 도입할 수 있어요! (미아역 - 미아사거리역), (미아 사거리역 - 길음역)의 느낌으로 가질 수 있습니다.
지금은 단순히 pk 기준 역 순서인데, 역 순서가 바뀐다면 pk 자체를 수정해야하는데 이는 innoDB에서 성능상 매우 좋지 않아요!

구간 엔티티 구현하고 리뷰 요청 주세요~

2023-08-21 05:10 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/SectionService.java
> +    }
validate 함수에서 바로 예외를 throw 하는 것은 어떤가요?

2023-08-21 05:10 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Line.java
> +    }
`stations`에서도 삭제 및 추가 해줘야할 것 같아요.

2023-08-24 07:58 UTC, jung-woo-kim approved these changes
코드 잘봤습니다 ㅎㅎ
싱준의 눈부신 성장 놀랍네요 🫢

약간의 리뷰 남겨봤는데 확인하시고 다음 스텝 진행하시면 될 것 같아요!

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
모든 Section의 지하철 상행역 하행역이 똑같은 상행역 하행역으로 바뀌는 메서드 인가요??

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
domain -> dto -> domain -> dto의 순환식 구조가 좋지 않다고 생각하기 때문에 보통 저는 domain은 dto를 모르게 하는 편이에요.

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
추가로 하행역만 더하면 sections 리스트 index 0에 있는 처음 상행역은 더해지지 않을 것 같아요.

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
객체지향적인 코드 좋습니다 🙂

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Station.java
> +    private List<Section> sections;
Station이 자신이 속해있는 구간들을 가지고 올 필요가 있나요? 양방향으로 연관관계가 설정되어있는데 굳이 필요 없다면 단방향으로 설정해두는 것을 고려해볼 수 있을 것 같아요.

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Station.java
>      }
equals 재정의 좋네요! 혹시 JPA Entity equals 관련 공부한 부분이 있다면 공유해주세요!

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Line.java
>      }
스터디 때 언급했던 것 같은데, 보통 oneToMany 관계에 있는 List는 add나 delete 형식으로 더해주고 이렇게 아예 변경하는 것을 지양해야해요. 이유는 상진형 pr에 있습니다!
```suggestion
    public void addSection(Section section) {
        this.sections.addSection(section);
    }
```

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
> +        sections.addSection(Section.createSection(line, upStation, downStation));
굳이 Sections 객체를 만들고 추가해주기 보다는 그냥 Section 객체를 만들고 추가해주는게 좋을 것 같아요.

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/SectionService.java
> +        line.getSections().addSection(Section.createSection(line, upStation, downStation));
디미터 법칙이 정해지고 있지 않은 것 같아요.
line 객체에 addSection 메서드를 새롭게 만드는 것은 어떤가요?

2023-08-24 07:58 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/SectionService.java
> +        line.getSections().deleteSection(station);
위 리뷰와 마찬가지입니다~

2023-08-24 08:01 UTC, jung-woo-kim approved these changes
추가 리뷰 남깁니다~

2023-08-24 10:53 UTC, shinsj4653 commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
헛 잘못 작성했네요ㅋㅋ수정하겠습니다

2023-08-24 11:55 UTC, merged

2023-08-24 14:56 UTC, shinsj4653 commented on src/main/java/kuit/subway/service/SectionService.java
> +        line.getSections().deleteSection(station);
Week2의 Step2 미션인 구간 삭제 제약 사항 변경 및 예외처리와 함께 이 사항을 고쳐서 업로드하겠습니다!

2023-08-24 14:56 UTC, shinsj4653 commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
list 내에 삽입되는 방식은 변경하였습니다. domain -> dto -> domain -> dto 를 없앨 수 있는 방법은 추후 고민해보겠습니다.