[1차 과제 - Step3] 이재현
KUIT-1/atdd-subway pull request #16
Opened 2023-08-24 07:57 UTC by versatile0010

## Section 도메인 
- downStation (하행역) 과 다대일 관계
- upStation (상행역) 과 다대일  관계
- line(노선) 과 다대일 관계

## 일급 컬렉션 Sections
- 노선이 가지는 구간 리스트를 감싼 Sections 클래스를 구현하여, 로직을 관리
- 구간 리스트에 관한 핵심 로직들은 Sections 내에서 관리
- line(노선) 은 Sections 객체를 값 타입으로 가진다.

## 구간 추가 flow
1. (Controller) 노선 id 와 상행역 id, 하행역 id 를 받는다.
2. (Line Service) 해당 노선에 대한 구간 추가 메서드 (line.addSection )를 통해
3. (Domain : sections) sections.add 를 호출한다.
4. (Domain : sections.add) 에서 전달받은 구간에 대한 검증 작업 이후, 이상 없으면 구간 추가
5. (Line Service) 하행 종점역 갱신

![image](https://github.com/KUIT-1/atdd-subway/assets/96612168/9ee606c5-8125-4220-977b-1666dd5e55a8)

## 구간 삭제 flow
1. (Controller)  노선 id 와 삭제할 구간 id 를 받는다.
2. (Line Service) 해당 노선에 대한 구간 삭제 메서드 (line.removeSection)를 통해
3. (Domain : sections) sections.remove 를 호출
4. (Domain : sections.remove) 검증 작업 이후 이상이 없으면 구간 삭제
5. (Line Service) 하행 종점역 갱신
![image](https://github.com/KUIT-1/atdd-subway/assets/96612168/866feb82-51cd-4b78-8a8d-e7a790e6e1d2)

## Exception 관련
- CustomExceptionContext enum 클래스를 구현하여 예외 메세지, 에러 코드를 한 곳에서 관리하도록 함.

감사합니다 :)

2023-08-24 08:08 UTC, jung-woo-kim requested changes
코드 잘봤습니다 ㅎㅎ
객체지향적인 개발 멋지군요..🫢

다만 라인 조회 시에 아직 지하철 노선에 포함된 역들이 아니라, 지하철 상행 종점 하행 종점만 반환하고 있는 것 같아서 해당 요구사항만 충족 시켜서 다시 request 해주세요!

2023-08-24 08:08 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Line.java
> +    }
Sections를 가지고 있다면 굳이 column을 가지고 downStation을 가지고 있을 필요가 있을까요?
하행 종점역은 이제 Sections를 통해 알 수 있을 것 같아요.

2023-08-24 08:08 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
> +
위에 못남겼는데 `getStationPair` 는 private로 해도 좋을 것 같아요.

2023-08-24 09:02 UTC, versatile0010 commented on src/main/java/kuit/subway/domain/Line.java
> +    }
아!!! 그러네요 🥲
미처 생각못했어요..

2023-08-24 12:45 UTC, jung-woo-kim approved these changes
리뷰 반영확인했습니다 :)
남긴 리뷰 확인해주시고 merge 해주세요~

2023-08-24 12:45 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
>          return LineInfoResponse.from(line, stations);
지금은 바로 N+1 문제 없이 조회가 될 것 같긴한데, 모든 line을 조회하는 api 가 생기면 N+1 문제가 생길 수 있으니 한번 고려해보면 좋을 것 같아요~

2023-08-25 06:19 UTC, merged

2023-08-25 06:20 UTC, versatile0010 commented on src/main/java/kuit/subway/service/LineService.java
>          return LineInfoResponse.from(line, stations);
리뷰 감사합니다!!
모든 라인을 조회하는 등의 N+1 이 발생할 수 있는 API 가 생기면
fetch join 으로 최적화를 해봐야겠네요! 🔥