[1차 과제 - Step3] 강지윤
KUIT-1/atdd-subway pull request #18
Opened 2023-08-24 21:16 UTC by kwiyoon

## 구조
Line은 여러개의 Section을 가진다.
Section은 downStation과 upStation을 가진다.
![image](https://github.com/KUIT-1/atdd-subway/assets/43175569/dc366de7-6d44-4a17-aeb7-0dab274d6d57)
+ Line이 삭제되면 Section도 함께 삭제
+ Section이 삭제되어도 Station은 유지

---

## 리팩토링
### DTO 기본 생성자의 AcessLevel = private
이름을 기반으로 getter 또는 setter를 이용해서 DTO필드를 가져온 후, reflection을 이용해서 DTO에 값을 주입
결과적으로 setter와 getter중에 하나 그리고 reflection을 위한 기본생성자가 필요하다.
- `@NoArgsConstructor(access = AccessLevel.PRIVATE)`
  - DTO의 확장 가능성이 없을 경우엔 PRIVATE로 설정.
  - 추후 상속할 시에 `PROTECTED`로 수정하는 방향

### Sections 일급컬렉션 활용
`List<Section>`관련 로직이 모두 `Line` 엔티티에서 이루어짐.
`List<Section>`를 일급컬렉션을 이용하여 관리 (Sections)

### test - 커스텀한 응답코드도 비교
- 404가 뜨면 테스트를 통과하도록 설계 -> 잘못된 예외처리로 404가 떠도 그냥 통과함
  - 적합한 처리가 되었는지 확인 필요성
  - 예시 `assertEquals(NONE_LINE.getResponseCode(), response.jsonPath().getLong(RESPONSECODE));`

### entity 객체 자체를 넘기던 방식 -> id만 넘기는 방식으로
검증 등의 코드에서 객체 자체를 넘기던 방식에서 id만 넘기는 방식으로 (아마 대부분) 수정.
-> 적합한 위치에 검증 코드를 두어 중복 코드를 최소화함

2023-08-26 17:42 UTC, jung-woo-kim requested changes
코드 잘봤습니다! ㅎㅎ
구조에 대해서 한번 이야기 해보고 가는 시간이 필요한 것 같아서 일단 rc 날립니다.
추가적으로 Sections 코드가 복잡해지니 단위테스트 추가해보는 것도 좋을 것 같아요!

상진형님도 의견 남겨주시면 구조 개선에 도움 될 것 같습니다~
리뷰 확인 후 수정 및 공부 / 구조에 대한 생각 및 이유도 남겨주시면 좋을 것 같아요!

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
> +        );
station의 equals 메서드가 오버라이드 되지 않고 사용되고 있네요.

JPA Entity에서 equal 사용 시에 문제가 되는 부분이 몇가지 있는데, 아래 링크와 내부에 참고 링크 한번 참고해보세요!

[JPA Entity Equals](https://github.com/jung-woo-kim/Atdd-Subway/issues/18)

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
> +        );
그래서 개인적인 생각으로는 이 메서드가 잘 동작하지 않을 것 같은데, 잘 동작하는지도 궁금해요!

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
> +    private final SectionService sectionService;
`SectionRepository`와 `SectionService` 를 둘다 의존성 주입 받고있는데, 그다지 좋아보이지 않아요.
추가로 `SectionService`에서  `LineService`의 기능이 필요해진다면, 객체 순환 참조로 가장 피해야하는 설계 중 하나에요.
[객체지향과 이를 지키기 위한 방법, 오브젝트 3/6 순환 참조 관련 내용 포함](https://www.linkedin.com/pulse/004-%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%EA%B3%BC-%EC%9D%B4%EB%A5%BC-%EC%A7%80%ED%82%A4%EA%B8%B0-%EC%9C%84%ED%95%9C-%EB%B0%A9%EB%B2%95-%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8-36-%ED%98%84%EC%9E%AC-%EC%9D%B4/?originalSubdomain=kr)

Service 의 기능이 중복되는 것을 막고 싶다면 아래 링크를 한번 참조해보는게 좋아보여요.
[Service에서 다른 Service 의존에 대하여](https://jangjjolkit.tistory.com/62)

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
> +    }
이렇게 메서드로 확인하는 것도 좋은 방법이긴 한데, 만약 동시에 생성 요청이 들어온다면 어떻게 될지 한번 고민해보면 좋을 것 같아요.

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/SectionService.java
> +    }
Transaction이 설정되어있지 않은 것 같아요.
Service에서 엔티티를 파라미터로 받는 것도 문제가 있다고 생각돼요.
영속 상태의 엔티티를 보내줄 지, 준영속 상태의 엔티티를 보내줄 지 모르는 상태에서 위처럼 사용하는 것은 위험하고 재사용성이 상당히 떨어지는 것 같아요. (Service와 엔티티 사이에 강결합 형성)

2023-08-26 17:42 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
>      }
Delete Request는 클라이언트 입장에서 보면 상행선 하행선을 삭제해주는 것이 아니라, 역 하나를 삭제해준다고 요청을 주는 것이 맞을 것 같아요. 즉, 삭제할 역 id 만 request에 포함되겠죠?

2023-08-27 06:00 UTC, kwiyoon commented on src/main/java/kuit/subway/domain/Line.java
> +    private final static String UP = "up";
넹!

2023-08-27 06:01 UTC, kwiyoon commented on src/main/java/kuit/subway/domain/Line.java
> +    }
넵 고민해보겠습니다!!

2023-08-27 06:05 UTC, kwiyoon commented on src/main/java/kuit/subway/domain/Sections.java
> +        );
잘 동작하긴 하는데, 해당 부분 공부해보겠습니다!

2023-08-27 06:12 UTC, kwiyoon commented on src/main/java/kuit/subway/service/LineService.java
> +    private final SectionService sectionService;
넵!! 해당 링크들 참고하여 열심히 고민해보겠습니다. 감사합니다!!

2023-08-27 06:14 UTC, kwiyoon commented on src/main/java/kuit/subway/service/SectionService.java
> +    }
다른 transaction이 설정된 메서드에서만 사용한다는 생각을 가지고 이렇게 설계한 것이긴 한데, 위에서 언급해주셨던 구조 해결한 후, 이 부분도 다시 고민해보겠습니다!!

2023-08-27 06:15 UTC, kwiyoon commented on src/main/java/kuit/subway/service/LineService.java
>      }
앗 그렇네요!? 넵!

2023-08-27 10:08 UTC, sanggenie reviewed
코드 잘 봤습니다 !
부족한 지식이지만 리뷰 남겨봐요 !
리뷰하면서 저도 많이 배워갑니다.😊

2023-08-27 10:08 UTC, sanggenie commented on src/main/java/kuit/subway/service/LineService.java
> +    private final SectionService sectionService;
추가적으로, 저는 아직까지는 SectionService, SectionRepository를 따로 관리하기 보단, Sections내에서 비즈니스 로직을 모두 처리하도록 구현했습니다.

이유는 다음과 같습니다.

1. SectionService단을 따로 만들게 되면, SectionController, 혹은 LineController에서 이를 추가로 의존하여 사용해야합니다. 의존관계가 복잡해지거나, 따로 관리해야되는 대상이 많아집니다.
2. 일급컬렉션 Sections을 통해 비즈니스와 관련된 메서드를 정의하고, 이를 Line 객체와의 메시지를 주고 받으면 더욱 객체지향적으로 구현할 수 있을 것 같습니다.

근데 이건 지극히 주관적인 생각이여서 의견 공유하는 정도로 받아들여주시면 좋을 것 같아요 !

2023-08-27 16:59 UTC, kwiyoon commented on src/main/java/kuit/subway/domain/Sections.java
> +        );
equals()에 직접적으로 int형을 넣게 되면 `false`가 뜨지만, 
해당 메서드인 `hasStation(Long stationId)`에서는 Long 타입이 들어가기 때문에 
Long형으로 자동 boxing되어 값이 같은 경우엔 `true`가 나온다고 합니다.

2023-08-27 17:24 UTC, kwiyoon commented on src/main/java/kuit/subway/domain/Sections.java
> +        );
section.getUpStation().equals(staion) 과 같이 Entity 객체 자체를 비교하게 될 경우에 언급해주신 문제가 발생할 거 같습니다. 
현재는 Long 만 비교하기 때문에, Long 타입의 stationId와 Long 타입인 getId()가 같은 Long이기 때문에 클래스를 비교하는 부분에서 통과 처리가 되는 거 같습니다.

2023-08-28 09:53 UTC, jung-woo-kim approved these changes
호오오 코드 완전 깔끔해졌네요!
엄청난 공부량.. 존경쓰 합니다...😮
제가 드린 리뷰가 정답이 아닐 수도 있어서 항상 비판적으로 받아주세요! ㅋㅋㅋ

코드 변경 확인했고, 매우 고생하셨습니다 👍👍

2023-08-28 09:53 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Section.java
> +    }
연관관계 설정 메서드 👍👍

2023-08-28 10:56 UTC, merged