[2차과제 - Step1] 이상진
KUIT-1/atdd-subway pull request #24
Opened 2023-08-26 16:45 UTC by sanggenie

Step1에서는 Mockist가 되어 테스트코드를 작성하였습니다.
Step2에서 Classicist가 되어 테스트코드를 작성하겠습니다 !

---

## 구간 추가 제약사항 변경
- [x]  기존에는 마지막 역을 기준으로만 구간 추가 → 위치와 상관 없이 추가 가능
  - [x]  새로운 역을 상행 종점으로 등록할 경우 맨 상위 구간으로 추가
  - [x]  새로운 역을 하행 종점으로 등록할 경우 맨 하위 구간으로 추가
     - 현재 요청받은 `section`의 `upStation`과 `downStation`에 대해  `findFirstUpStation`과, `findLastDownStation` 둘 중 하나와 동일한 경우는 `sections.add()`를 통해 단순히 리스트에 추가하는 작업을 진행
  - [x]  사이에 끼울 경우 각 기존 구간의 상행역 or 하행역을 신규 구간 정보로 잘 변경
     - 기존의 `sections`의 `upStation`을 탐색하며, 요청받은 `upStation`과 같은 경우,
        - 거리 예외처리를 진행하고,
        - 기존 `section`의 `upStation`을 요청받은 `downStation`으로 변경
   
         ![image](https://github.com/KUIT-1/atdd-subway/assets/97597051/b9334d97-52e6-46e7-820b-dd1fd0493313)
         (위의 사진과 같은 느낌으로 `sections`를 관리 !)
- [x]  **노선 조회 시 상행 종점을 기준으로 역들이 잘 정렬되어 반환되어야 함**
   ```java
    public List<Station> getStations() {
        List<Station> stations = new ArrayList<>();
        Station upStation = findFirstUpStation();
        Station downStation = null;
        stations.add(upStation);

        Optional<Section> section = findSection(upStation);

        while (section.isPresent()) {
            downStation = section.get().getDownStation();
            stations.add(downStation);
            section = findSection(downStation);
        }

        return stations;
    }
   ```
   - `findFirstUpStation()`을 `stations`에 추가하고,
   - 현재 `upStation`에 해당하는 `Section`을 `Optional`로 받아온 후,
   - 만약 `Optional` 값이 존재한다면, 현재 섹션의 `downStation`을 계속해서 `stations`에 추가하여 정렬된 노선 리스트를 구현

## 구간 추가 예외
- [x]  상행역과 하행역 둘 중 하나도 포함되어있지 않으면 추가 불가
   - 컨트롤러단에서 해결 `(findById().orElseThrow())`
- [x]  상행역과 하행역이 이미 노선에 모두 등록되어 있다면 추가 불가
   - `validateDuplicatedSection` 에서 검증
   ```java
    private void validateDuplicatedSection(Section section) {
        if (isExistedUpStation(section) && isExistedDownStation(section)) {
            throw new SubwayException(EXISTED_STATION_IN_SECTIONS);
        }
    }

    private boolean isExistedUpStation(Section section) {
        return sections.stream().anyMatch(existedSection ->
                section.getUpStation().equals(existedSection.getUpStation()) || section.getUpStation().equals(existedSection.getDownStation()));
    }

    private boolean isExistedDownStation(Section section) {
        return sections.stream().anyMatch(existedSection ->
                section.getDownStation().equals(existedSection.getUpStation()) || section.getDownStation().equals(existedSection.getDownStation()));
    }
   ```
   - 기존에 존재하는 `sections`를 탐색하며, 추가하고자 하는 `section`의 `upStation`과 동일한 `station`을 포함하고,
   - 기존에 존재하는 `sections`를 탐색하며, 추가하고자 하는 `section`의 `downStation`과 동일한 `station`을 포함하면 예외 발생
   
- [x]  역 사이에 새로운 역을 등록할 경우 기존 역 사이 길이보다 크거나 같으면 추가 불가
   - `validateSectionDistance` 에서 검증

2023-08-26 17:55 UTC, jung-woo-kim requested changes
코드 잘봤습니다 ㅎㅎ
코드 구조나 리팩토링할 부분도 거의 보이지 않는 완벽한 코드였던 것 같아요..
다만, 제가 보기에 비즈니스 로직에 조금 치명적일 수 있는 부분이 있는 것 같아 그 부분만 확인하면 좋을 것 같아 rc 남깁니다!

코드 보면서 저도 많이 배워갑니다 ㅎㅎ
고생 많으셨어요!

2023-08-26 17:55 UTC, jung-woo-kim commented on src/main/java/kuit/subway/line/domain/Sections.java
> +    }
station의 equals 메서드가 오버라이드 되지 않고 사용되고 있네요.

JPA Entity에서 equal 사용 시에 문제가 되는 부분이 몇가지 있는데, 아래 링크와 내부에 참고 링크 한번 참고해보세요!

[참고 링크](https://github.com/jung-woo-kim/Atdd-Subway/issues/18)

추가로 저는 비슷한 상황에서 프록시 객체 equals 비교가 잘 동작하지 않았어서 잘 됐다면 왜 잘 됐는지도 한번 고민해보시고 공유해주시면 좋을 것 같아요!

2023-08-26 17:55 UTC, jung-woo-kim commented on src/main/java/kuit/subway/line/domain/Sections.java
> +    }
만약에 DownStation에 상행역을 추가하는 경우는 어떤가요??
가령, A-B-D 가 있을 때 C-B의 요청이 들어온다면 어떻게 되나요?

2023-08-27 10:14 UTC, sanggenie commented on src/main/java/kuit/subway/line/domain/Sections.java
> +    }
세상에나.. 제대로 작동하지 않네요ㅜㅜ
놓쳤던 부분 캐치해주셔서 감사합니다😊

2023-08-27 14:06 UTC, jung-woo-kim approved these changes
변경사항 확인했습니다~
지윤님 리뷰 남기시면 merge하고 진행해주시면 될 것 같아요!

p.s. equals 예상되는 바로는 지금은 같은 객체일 때만 equals가 True로 나오고, Sections를 한번에 불러오니 영속성 컨텍스트에서 같은 객체가 반환되고 있는 것이 아닐까? 생각 됩니다!

2023-08-27 14:11 UTC, jung-woo-kim reviewed
추가로, 다른 분들 리뷰 드릴 때도 신경을 못쓴 부분인데, Line -> Sections를 부를 때 쿼리 한번, Sections에서 관련된 Station을 부를 때 Section 개수가 N이라면 2N번 쿼리가 나갈 것 같은데 이 부분 해결된건지 궁금해요!

2023-08-27 15:17 UTC, kwiyoon reviewed
stream 사용에 감탄하면서 봤어요.. 많이 배워갑니다..!! 덕분에 mock test부분도 많이 감을 잡은 거 같아요. 코드를 보고 나면 제 구현도 남의 코드를 따라가게 되는 경향이 있어서... 별로 선호하지 않는데, 배울점이 많아서 확실히 앞으로의 구현에 많은 도움이 될 거 같아요..
아이디어는 최대한 제 아이디어로 하되, stream 사용이나 역할 분담 등등.. 조금씩 참고해도 괜찮을까요!?ㅎㅎ 많이 배워가요!!!


+첫번째 남긴 리뷰처럼.. 새롭게 알게 되는 부분들에 커멘트 남기려고 했는데, 그냥 코멘트 도배를 하게 될 거 같아서.. 하나 하고 멈췄어요 ㅎㅎ...

2023-08-27 15:29 UTC, sanggenie commented
> 추가로, 다른 분들 리뷰 드릴 때도 신경을 못쓴 부분인데, Line -> Sections를 부를 때 쿼리 한번, Sections에서 관련된 Station을 부를 때 Section 개수가 N이라면 2N번 쿼리가 나갈 것 같은데 이 부분 해결된건지 궁금해요!

으윽........
기능 구현에 눈이 돌아가 N+1 문제를 생각하지 못하고 있었습니다..🥲
쿼리 수를 확인하니 어마어마한 상태입니다.
특히나 중간에 구간을 추가할 시, 굉장히 많은 쿼리가 발생하는데 이 부분은 다음 스텝, 혹은 이번 주 과제 마무리까지 해결해보겠습니다 !

2023-08-27 15:31 UTC, sanggenie commented
> stream 사용에 감탄하면서 봤어요.. 많이 배워갑니다..!! 덕분에 mock test부분도 많이 감을 잡은 거 같아요. 코드를 보고 나면 제 구현도 남의 코드를 따라가게 되는 경향이 있어서... 별로 선호하지 않는데, 배울점이 많아서 확실히 앞으로의 구현에 많은 도움이 될 거 같아요.. 아이디어는 최대한 제 아이디어로 하되, stream 사용이나 역할 분담 등등.. 조금씩 참고해도 괜찮을까요!?ㅎㅎ 많이 배워가요!!!
> 
> +첫번째 남긴 리뷰처럼.. 새롭게 알게 되는 부분들에 커멘트 남기려고 했는데, 그냥 코멘트 도배를 하게 될 거 같아서.. 하나 하고 멈췄어요 ㅎㅎ...

얼마든지 참고하셔도 괜찮습니다 !
하지만 저도 그렇게 잘 짠 코드는 아니라 해당 코드가 정답이 아닐 수 있습니다..!
리뷰 감사드립니다😄

2023-08-27 15:34 UTC, merged

2023-08-31 07:56 UTC, versatile0010 commented
구간 추가 로직을 최대한 혼자 구현하려다가 결국에는 잘 안되어서.. 
공부하러 왔습니다.. 🥲🥲
상진님 코드 보면서 stream 을 잘 다룰 수 있는게 얼마나 중요한 지 깨닫고 갑니다!!
감탄하면서 봤어요,, 많이 배웠습니다 🔥🔥