[2차 과제 - Step2] 신성준
KUIT-1/atdd-subway pull request #27
Opened 2023-08-30 07:48 UTC by shinsj4653

2차 과제 - Step1 의 리뷰를 기다리면서 경로 조회 및 예외처리까지 구현하였지만, 경로 조회 MockTest에서 막히는 부분이 있어서 우선 지금까지 한 내용을 정리하여 올리겠습니다!

# Tasks
## 1. 구간 삭제 제약 사항 변경
### - 위치에 상관없이 삭제 가능
맨 마지막 구간만 삭제가 가능했지만, 이제는 아래의 변경사항들을 적용해줬다.

### - 종점이 제거될 경우 다음으로 오던 역이 종점이 되도록 구현
(upStation, downStation) 구조로 구간이 구성되어 있으므로, 다음과 같은 validate 함수를 거친 후, 조건을 만족시 구간 리스트의 맨 끝 요소를 삭제해줬다. 삭제하면, 자연스럽게 이전의 구간의 downStation 이 종점이 된다.
```java
 private Boolean verfiyIsLastStationDelete(Station deleteStation) {
     return this.sections.get(sections.size() - 1).getDownStation().equals(deleteStation);
}

// 만약, 위의 검증 사항 통과 시, 
this.sections.remove(sections.size() - 1); // 해당 코드 실행
```

### - 중간역이 제거될 경우 재배치해야한다.
(A, B), (B, C) 로 구간 리스트가 구성되어 있을 때, B역을 제거한다고 가정해보자.
```java
// 주어진 역을 이미 상행역으로 가지고 있는 구간 반환
    private Optional<Section> findMatchUpSection(Station upStation) {
        return this.sections.stream()
                .filter(s -> s.getUpStation().equals(upStation))
                .findFirst();
    }

    // 주어진 역을 이미 하행역으로 가지고 있는 구간 반환
    private Optional<Section> findMatchDownSection(Station downStation) {
        return this.sections.stream()
                .filter(s -> s.getDownStation().equals(downStation))
                .findFirst();
    }

Section findSection = findMatchDownSection(deleteStation).get();
                
// 거리 계산을 위해 다음 구간 가져오기
Section nextSection = findMatchUpSection(deleteStation).get();
                
 // 거리 계산까지 하여 findSection 업데이트
findSection.updateSection(findSection.getUpStation(), nextSection.getDownStation(), findSection.getDistance() + nextSection.getDistance());

// 업데이트 구간의 다음 구간 삭제
this.sections.remove(nextSection);
```
구간의 하행역을 기준으로 원하는 구간을 찾아주는 `findMatchDownSection` 함수로 업데이트 하려는 구간을 찾아준다. 구간의 거리값도 업데이트 해줘야하므로, 다음 구간을 찾아야하는데 이는 상행역을 기준으로 구간을 찾아주는 `findMatchUpSection` 함수를 이용하면 된다.  
삭제하려는 역을 하행역으로 가지고 있는 구간의 하행역을 다음 구간의 하행역으로, 그리고 기존 구간의 거리를 두 구간 거리의 합으로 업데이트 시켜줬다.

## 2. 구간 삭제 예외
### - 노선에 등록되어 있지 않은 역은 제거 불가
```java
 // 노선에 등록되어 있지 않은 역은 제거 불가
    private void validateSectionDeleteStationNotExist(Station deleteStation) {
        if (findMatchUpSection(deleteStation).isEmpty() && findMatchDownSection(deleteStation).isEmpty())
            throw new InvalidSectionDeleteStationNotExist();
    }
```
삭제하려고 하는 역을 상행역 혹은 하행역으로 가지고 있는 구간이 모두 존재하지 않는다면, `throw new InvalidSectionDeleteStationNotExist();` 로 예외처리를 해줬다.

### - 구간이 하나인 노선에서 구간 제거 불가
sections.size() 가 1일 경우, `throw new InvalidSectionDeleteOnlyTwoStationsException();` 코드를 통해 예외처리를 해줬다.

# Refactor & TIL
## 1. 디미터 법칙 적용
참고자료 - https://dkswnkk.tistory.com/687  
  
다른 객체에 어떠한 자료(내부 구조) 를 가지고 있는지 숨기고, 함수를 통해 공개하게 만드는 코드 작성 법칙이다.  
```java
// LineReadResponse.java
public static LineReadResponse of(Line line) {
        return LineReadResponse.builder()
                .id(line.getId())
                .name(line.getName())
                .color(line.getColor())
                .stations(line.getSections().getOrderStations())
                .distance(line.getDistance())
                .build();
    }
```
기존의 Line 조회 응답 dto 생성 함수이다. line 엔티티의 sections 정보를 가져온 다음, sections내에서 정렬된 역 리스트를 반환해주는 방식이었다.
```java
// LineReadResponse.java
public static LineReadResponse of(Line line) {
        return LineReadResponse.builder()
                .id(line.getId())
                .name(line.getName())
                .color(line.getColor())
                .stations(line.getStations())
                .distance(line.getDistance())
                .build();
    }

// Line.java
 public List<StationReadResponse> getStations() {
        return this.sections.getOrderStations();
    }
```
디미터 법칙을 지키기 위해, 다음과 같이 line 엔티티 내에 getStations 함수를 생성한 후, 해당 함수 내에서 sections의 정렬된 역들을 반환해주는 함수를 호출해주는 방식으로 수정하였다.

# Trouble Shooting
## 1. addSection -> null pointer exception 
경로 조회 MockTest를 하다가 다음 코드에 오류가 났다.
```java
// ------ LineServiceMockTest.java ------
@InjectMocks
    private LineService lineService;

    @Mock
    private LineRepository lineRepository;

    @Mock
    private StationRepository stationRepository;

@Nested
    @DisplayName("노선 내 경로 조회 Mock 테스트")
    class FindPath {
        Station station1;
        Station station2;
        Station station3;

        @BeforeEach
        void setUp() {
            station1 = Station.createStation("강남역");
            station2 = Station.createStation("수서역");
            station3 = Station.createStation("논현역");
        }

        @Nested
        @DisplayName("정상 케이스")
        class SuccessCase {

            @Test
            @DisplayName("출발역 id와 도착역 id로 요청하면 출발역, 도착역까지의 경로에 있는 역 목록, 그리고 경로 구간의 총 거리가 검색된다.")
            void findLineSuccess() {

                Station station1 = Station.createStation("강남역");
                Station station2 = Station.createStation("수서역");
                Station station3 = Station.createStation("논현역");
                // given
                given(stationRepository.findById(1L)).willReturn(Optional.of(station1));
                given(stationRepository.findById(2L)).willReturn(Optional.of(station2));
                given(stationRepository.findById(3L)).willReturn(Optional.of(station3));

                Line line = Line.createLine("와우선", "green", 20);
                given(lineRepository.save(line)).willReturn(line);
                given(lineRepository.findById(1L)).willReturn(Optional.of(line));

                // when

               // addSection 에서 null pointer exception 오류 발생!!
                lineService.addSection(1L, new SectionCreateRequest(1L, 2L, 10));
                lineService.addSection(1L, new SectionCreateRequest(2L, 3L, 10));
                PathReadRequest req = new PathReadRequest(1L, 3L);
                PathReadResponse res = lineService.findPath(line.getId(), req);

                StationReadResponse stationRes1 = res.getStations().get(0);
                StationReadResponse stationRes2 = res.getStations().get(1);
                StationReadResponse stationRes3 = res.getStations().get(2);

                // then
                assertThat(res).isNotNull();
                assertThat(res.getStations()).containsExactly(stationRes1, stationRes2, stationRes3);
                assertEquals(20.0, res.getTotalDistance());
                verify(lineRepository, times(1)).findById(anyLong());
                verify(stationRepository, times(3)).findById(anyLong());
            }
        }
// -----------------------------------

// ----- Line.java ------
public void addSection(Section section) { 
        this.sections.addSection(section);
    }
// -----------------------------------

// ----- Sections.java ------
 public void addSection(Section section) {
        // 구간을 처음 추가하는 경우는 validate 할 필요 X
        if (sections.size() == 0) {
            this.sections.add(section);
        } else {
            validateSectionCreateBothNotExist(section);
            validateSectionCreateBothExist(section);

...

private void validateSectionCreateBothNotExist(Section section) {
        boolean upStationExist = sections.stream().anyMatch(existedSection ->
                existedSection.getUpStation().equals(section.getUpStation()) || existedSection.getDownStation().equals(section.getUpStation()));
        boolean downStationExist =sections.stream().anyMatch(existedSection ->
                existedSection.getUpStation().equals(section.getDownStation()) || existedSection.getDownStation().equals(section.getDownStation()));
        if (!upStationExist && !downStationExist) {
            throw new InvalidSectionCreateBothNotExistExcpetion();
        }
    }
// -----------------------------------

// ----- Station.java ------
 @Override
    public boolean equals(Object o) {
        if (!(o instanceof Station)) {
            return false;
        }
        Station station = (Station) o;
        return station.getId().equals(id) && station.getName().equals(name);
    }  
// -----------------------------------
```
테스트 내에서, line.addSection을 하는 순간, Station 의 equals 함수에서 station.getId() 값이 null인 오류가 발생한다.
MockTest를 아직 완벽히 이해를 하지 못한 것 같아서 좀 더 고민을 하여 Step3 PR에  [...]

2023-08-30 14:13 UTC, jung-woo-kim requested changes
코드 잘봤습니다 ㅎㅎ
복잡한 코드와 N+1 발생 문제의 가능성이 보여 우선 rc 남깁니다!
리팩토링된 코드 기대하겠습니다!
근데 일단 다른거 다필요없고, 회사 다니면서 이만큼 하는거 리스펙입니다.....

p.s. 싱준은 Classist인가요 Mockist인가요?ㅋㅋㅋ

2023-08-30 14:13 UTC, jung-woo-kim commented on src/main/java/kuit/subway/domain/Sections.java
여기 전체적으로 코드가 너무 복잡한데, 다음과 같은 규칙을 의식적으로 적용해본 후에 다시 한번 리뷰 남겨볼게요!
1. if-else 문을 쓰지 않는다. (switch case도 마찬가지, if-else문은 가독성을 해쳐요!)
2. 함수 메서드의 depth는 1로 제한한다. (중첩 for, if 문은 가독성을 해쳐요!)

관련해서 UMC 1기 객체지향 미션 남겼는데, 아래 객체지향 체조 9단계 참고하면서 개발하시면 도움될거에요!
[UMC 1기 1주차 미션](https://ku-cando-it.notion.site/1-1-a95f391ec54d4ada91840048f447f35d?pvs=4)

2023-08-30 14:13 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
> +        line.addSection(Section.createSection(line, upStation, downStation, res.getSectionDistance()));
Section에도 line으로 연관관계 설정해준 부분 좋습니다 👍

2023-08-30 14:13 UTC, jung-woo-kim commented on src/main/java/kuit/subway/service/LineService.java
>      }
이 부분 쿼리가 몇회 나가나요? 
예상
- 전체 Line을 select 1회
- Line 마다의 section을 얻기 위해 section의 개수 만큼 N회
- section에 존재하는 Station을 얻기 위해 또 2N회

총 3N + 1회의 쿼리가 발생할 것 같은데, 확인 후 고쳐보시는 것을 권장드려요!

2023-08-31 00:15 UTC, rlagkswn00 commented on src/main/java/kuit/subway/domain/Sections.java
k..u...i...t...

2023-08-31 01:10 UTC, shinsj4653 commented on src/main/java/kuit/subway/domain/Line.java
> +    }
책임 분리 명시하겠습니다! 
구간은 Classic, 노선은 Mock 스타일로 해봤는데...아무래도 Classist 인 것 같네요 전;;ㅎㅎㅎ

2023-08-31 01:47 UTC, shinsj4653 commented on src/main/java/kuit/subway/domain/Sections.java
> +    }
아직 자바에도 익숙하지 않은 것 같네요ㅋㅋㅋㅋㅜㅜ많이 배워갑니다

2023-08-31 01:48 UTC, rlagkswn00 reviewed
어제 리뷰 했어야 했는데, 요새 자꾸 생각지 못한 일들이 생겨서 지금이라도 드립니다..!!
전체적으로 코드에 노력이 보이고, 진짜 일취월장이라는 단어가 딱 맞는 코드 변화 양상인거 같습니다.

고생하셨습니다!

2023-08-31 01:48 UTC, rlagkswn00 commented on src/main/java/kuit/subway/service/LineService.java
> +            result.add(LineReadResponse.of(line));
stream이 만사형통은 아니라고 생각하지만, 
다른 곳에서 steam으로 만들었으니 여기도 같이 수정해보는 게 어떤지 싶습니다!

2023-08-31 01:48 UTC, rlagkswn00 commented on src/main/java/kuit/subway/service/LineService.java
> +        Station upStation = validateStationExist(upStationId);
validateStationExist 메소드가 id값에 따른 Stations을 반환해주고 그 사이에 valid처리를 하는 것으로 이해하긴 했습니다.
다만, "validate"로 작성하면 메소드가 유효성 검사"만"진행하는 걸로 해석되서 검사와 검색을 나누는 것이 어떤지 싶습니다..!!!

2023-08-31 04:51 UTC, shinsj4653 commented on src/main/java/kuit/subway/service/LineService.java
> +            result.add(LineReadResponse.of(line));
stream 너무 조와요

2023-09-03 17:19 UTC, shinsj4653 commented on src/main/java/kuit/subway/service/LineService.java
>      }
우선은 batch size 덕분에 3번 나가긴 합니다. sections을 기준으로 fetch join을 해보고 싶은데 station이 2개라 감이 잘 안오네요...

2023-09-03 17:20 UTC, merged